### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Zeronova** [AzumattDev/AzuAutoStore#1]
If I press the point near chests and a fellow player, his character is destroyed.

**Comment by AzumattDev** [comment]
what? I'm not sure I understand.

**Comment by Zeronova** [comment]
I’ll phrase it differently ;-) When I press the auto-sort button and another player is nearby, their character gets deleted and they get a black screen. At first, we thought one would also be sorted into a box. XD

**Comment by Goldenrevolver** [comment]
I got a similar report for quickstacking in my mod a month ago. they even provided logs of the deleted person and the person pressing quickstack which did not have errors. it simply said 'Local player destroyed' for the destroyed person and 'Destroying old local player' for the person doing the quickstack, so the nview got the wrong ownership. it was a very heavy mod list though, so I assume some other mod is messing with every mod that accesses containers by making us access player nviews (which triggers Player.FixedUpdate and deletes the player). if you can provide a log file of yourself, the server and the other player @Zeronova that would be useful to compare it to the report I got

edit: it's probably adventure backpacks. it reuses the player nview

**Comment by Goldenrevolver** [comment]
okay, I reproduced this issue when someone wears an adventure backpack, and then the other person (standing in range) does a hotkey store of an item in their inventory (so not storing by dropping). then the player with the backpack gets deleted because the player who stores claims ownership of the local player nview.

when throwing an item on the ground to store it, the store attempt into the backpack is successful and the bug does not happen (you probably send a proper RPC for this one).

my fix in quickstackstore in version 1.4.5 for this behavior was making sure that the `container.nview.getcomponent<Player>` either does not exist (players always have their nview as a direct component) or IS the local player. so either the container is not an adventure backpack (or something similar) or its your own backpack (which is allowed in quickstackstore as people like quickstacking into their own backpack).

if you don't want to store into these player containers at all you can of course simply check that there is no Player component on the nview of the container at all. this needs to be done before claiming ownership

**Comment by AzumattDev** [comment]
Very interesting bug lol

Thank you for the info Golden. I appreciate that.

**Comment by Zeronova** [comment]
After removing Adventure Backpacks 1.7.2 the error is resolved. Sorry Azu, it's not your fault. Now using AzuEPI with 4 additional rows, I have to find a weight base mod, as well as MagicEitrBase. ;-)

log 4 [Goldenrevolver](https://github.com/Goldenrevolver)
[Player_bug.log](https://github.com/AzumattDev/AzuAutoStore/files/13253955/Player_bug.log)

**Comment by Goldenrevolver** [comment]
> After removing Adventure Backpacks 1.7.2 the error is resolved. Sorry Azu, it's not your fault. Now using AzuEPI with 4 additional rows, I have to find a weight base mod, as well as MagicEitrBase. ;-)
> 
> log 4 [Goldenrevolver](https://github.com/Goldenrevolver) [Player_bug.log](https://github.com/AzumattDev/AzuAutoStore/files/13253955/Player_bug.log)

thank you, but now that we figured it out, I'm sure Azu will have this fixed this weekend. It was not really Adventure Backpacks fault. It was just a dumb coincidence that my mod and AzuAutoStore interact with Adventure Backpacks in this way in this situation. so feel free to use Adventure Backpacks again when AzuAutoStore is updated
